# Generated by Django 3.0 on 2021-11-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=40)),
                ('date', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('price', models.CharField(max_length=40)),
                ('unit', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=40)),
                ('cname', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('amount', models.CharField(max_length=40)),
                ('duration', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
    ]
