# Generated by Django 3.0 on 2021-11-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('plan', models.CharField(max_length=60)),
                ('photo', models.ImageField(upload_to='myimages')),
                ('joindate', models.CharField(max_length=40)),
                ('expiredate', models.CharField(max_length=40)),
                ('initialamount', models.CharField(max_length=10)),
            ],
        ),
    ]
